plugin_order = [
        "disk_size",
        "no_partitions",
        "disk_lifespan",
        "no_files",
        "no_user_files",
        "file_types",
        "operating_system",
        "win_os_lifespan",
        "win_version",
        "win_user_info",
        "win_evt_logs",
        "win_screen_resolution",
        "win_apps",
        "win_no_user_lnk_files",
        "win_no_prefetch_files",
        "win_no_usbs",
        "win_browsers",
        "firefox_history",
        "chrome_history",
        "edge_history",
        "file_sizes",
        "plaso",
        "external_demo"
]

